name: Test SSH Connection
on:
  workflow_dispatch: # Esto permite ejecutarlo manualmente desde GitHub Actions
jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH connection to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Conexión exitosa desde GitHub Actions!"
            hostname
            whoami
